In [65]:
import pandas as pd
import numpy as np

In [66]:
Data=pd.read_csv("CarPrice_Assignment.csv")

In [67]:
X=Data
X

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [68]:
X= pd.get_dummies(X, columns=['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem'], drop_first=True)

In [69]:
X

car_ID  symboling                   CarName  wheelbase  carlength  \
0         1          3        alfa-romero giulia       88.6      168.8   
1         2          3       alfa-romero stelvio       88.6      168.8   
2         3          1  alfa-romero Quadrifoglio       94.5      171.2   
3         4          2               audi 100 ls       99.8      176.6   
4         5          2                audi 100ls       99.4      176.6   
..      ...        ...                       ...        ...        ...   
200     201         -1           volvo 145e (sw)      109.1      188.8   
201     202         -1               volvo 144ea      109.1      188.8   
202     203         -1               volvo 244dl      109.1      188.8   
203     204         -1                 volvo 246      109.1      188.8   
204     205         -1               volvo 264gl      109.1      188.8   

     carwidth  carheight  curbweight  enginesize  boreratio  ...  \
0        64.1       48.8        2548         130       3.47  ...   
1        64.1       48.8        2548         130       3.47  ...   
2        65.5       52.4        2823         152       2.68  ...   
3        66.2       54.3        2337         109       3.19  ...   
4        66.4       54.3        2824         136       3.19  ...   
..        ...        ...         ...         ...        ...  ...   
200      68.9       55.5        2952         141       3.78  ...   
201      68.8       55.5        3049         141       3.78  ...   
202      68.9       55.5        3012         173       3.58  ...   
203      68.9       55.5        3217         145       3.01  ...   
204      68.9       55.5        3062         141       3.78  ...   

     cylindernumber_three  cylindernumber_twelve  cylindernumber_two  \
0                   False                  False               False   
1                   False                  False               False   
2                   False                  False               False   
3                   False                  False               False   
4                   False                  False               False   
..                    ...                    ...                 ...   
200                 False                  False               False   
201                 False                  False               False   
202                 False                  False               False   
203                 False                  False               False   
204                 False                  False               False   

     fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0              False            False           False           False   
1              False            False           False           False   
2              False            False           False           False   
3              False            False           False           False   
4              False            False           False           False   
..               ...              ...             ...             ...   
200            False            False           False           False   
201            False            False           False           False   
202            False            False           False           False   
203            False            False            True           False   
204            False            False           False           False   

     fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0               True            False            False  
1               True            False            False  
2               True            False            False  
3               True            False            False  
4               True            False            False  
..               ...              ...              ...  
200             True            False            False  
201             True            False            False  
202             True            False       

In [74]:
X.drop("CarName",axis=1,inplace=True)

In [75]:
X

car_ID  symboling  wheelbase  carlength  carwidth  carheight  curbweight  \
0         1          3       88.6      168.8      64.1       48.8        2548   
1         2          3       88.6      168.8      64.1       48.8        2548   
2         3          1       94.5      171.2      65.5       52.4        2823   
3         4          2       99.8      176.6      66.2       54.3        2337   
4         5          2       99.4      176.6      66.4       54.3        2824   
..      ...        ...        ...        ...       ...        ...         ...   
200     201         -1      109.1      188.8      68.9       55.5        2952   
201     202         -1      109.1      188.8      68.8       55.5        3049   
202     203         -1      109.1      188.8      68.9       55.5        3012   
203     204         -1      109.1      188.8      68.9       55.5        3217   
204     205         -1      109.1      188.8      68.9       55.5        3062   

     enginesize  boreratio  stroke  ...  cylindernumber_three  \
0           130       3.47    2.68  ...                 False   
1           130       3.47    2.68  ...                 False   
2           152       2.68    3.47  ...                 False   
3           109       3.19    3.40  ...                 False   
4           136       3.19    3.40  ...                 False   
..          ...        ...     ...  ...                   ...   
200         141       3.78    3.15  ...                 False   
201         141       3.78    3.15  ...                 False   
202         173       3.58    2.87  ...                 False   
203         145       3.01    3.40  ...                 False   
204         141       3.78    3.15  ...                 False   

     cylindernumber_twelve  cylindernumber_two  fuelsystem_2bbl  \
0                    False               False            False   
1                    False               False            False   
2                    False               False            False   
3                    False               False            False   
4                    False               False            False   
..                     ...                 ...              ...   
200                  False               False            False   
201                  False               False            False   
202                  False               False            False   
203                  False               False            False   
204                  False               False            False   

     fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  fuelsystem_mpfi  \
0              False           False           False             True   
1              False           False           False             True   
2              False           False           False             True   
3              False           False           False             True   
4              False           False           False             True   
..               ...             ...             ...              ...   
200            False           False           False             True   
201            False           False           False             True   
202            False           False           False             True   
203            False            True           False            False   
204            False           False           False             True   

     fuelsystem_spdi  fuelsystem_spfi  
0              False            False  
1              False            False  
2              False            False  
3              False            False  
4              False            False  
..               ...              ...  
200            False            False  
201            False            False  
202            False            False  
203            False            False  
204            False            False  

[205 rows x 45 columns]

In [76]:
y=X.price

In [77]:
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...   
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [78]:
X.drop('price',axis=1,inplace=True)

In [79]:
X_std=(X-X.mean())/X.std()

In [80]:
X_std.drop("car_ID",axis=1,inplace=True)
X_std.drop("symboling",axis=1,inplace=True)

In [81]:
y_std=(y-y.mean())/y.std()

In [82]:
y_std

0      0.027324
1      0.403473
2      0.403473
3      0.084279
4      0.522389
         ...   
200    0.446659
201    0.722042
202    1.027468
203    1.150765
204    1.170167
Name: price, Length: 205, dtype: float64

In [83]:
x=X_std.values

In [84]:
Y=y_std.values

In [85]:
Y

array([ 2.73242539e-02,  4.03473402e-01,  4.03473402e-01,  8.42786174e-02,
        5.22389106e-01,  2.47005370e-01,  5.54934457e-01,  7.06395512e-01,
        1.32663479e+00,  5.73606350e-01,  3.94711192e-01,  4.56672533e-01,
        9.63003084e-01,  9.79901631e-01,  1.41300514e+00,  2.18846071e+00,
        3.50967677e+00,  2.95452819e+00, -1.01713115e+00, -8.73931609e-01,
       -8.38882770e-01, -9.64432718e-01, -8.63667306e-01, -6.65891714e-01,
       -8.82193121e-01, -8.24237362e-01, -7.09452414e-01, -5.90661884e-01,
       -5.45223568e-01, -3.91433660e-02, -8.50899515e-01, -8.03833931e-01,
       -9.86087894e-01, -8.44640793e-01, -7.69536138e-01, -7.48757183e-01,
       -7.48757183e-01, -6.73652528e-01, -5.23443218e-01, -5.54736824e-01,
       -3.73233907e-01, -4.15216801e-02, -3.66975186e-01, -8.12596140e-01,
       -5.45786853e-01, -5.45786853e-01, -2.78977565e-01,  2.37497060e+00,
        2.78804621e+00,  2.84437470e+00, -1.01162348e+00, -8.98966494e-01,
       -8.11344396e-01, -

In [86]:
x

array([[-1.68664293, -0.4254799 , -0.84271939, ...,  1.08401606,
        -0.21376243, -0.06984303],
       [-1.68664293, -0.4254799 , -0.84271939, ...,  1.08401606,
        -0.21376243, -0.06984303],
       [-0.70686548, -0.23094769, -0.19010076, ...,  1.08401606,
        -0.21376243, -0.06984303],
       ...,
       [ 1.71766854,  1.19562185,  1.3948302 , ...,  1.08401606,
        -0.21376243, -0.06984303],
       [ 1.71766854,  1.19562185,  1.3948302 , ..., -0.91799558,
        -0.21376243, -0.06984303],
       [ 1.71766854,  1.19562185,  1.3948302 , ...,  1.08401606,
        -0.21376243, -0.06984303]])

In [87]:
x.shape

(205, 42)

In [88]:
y.shape

(205,)

In [89]:
Y.reshape(-1,1)

array([[ 2.73242539e-02],
       [ 4.03473402e-01],
       [ 4.03473402e-01],
       [ 8.42786174e-02],
       [ 5.22389106e-01],
       [ 2.47005370e-01],
       [ 5.54934457e-01],
       [ 7.06395512e-01],
       [ 1.32663479e+00],
       [ 5.73606350e-01],
       [ 3.94711192e-01],
       [ 4.56672533e-01],
       [ 9.63003084e-01],
       [ 9.79901631e-01],
       [ 1.41300514e+00],
       [ 2.18846071e+00],
       [ 3.50967677e+00],
       [ 2.95452819e+00],
       [-1.01713115e+00],
       [-8.73931609e-01],
       [-8.38882770e-01],
       [-9.64432718e-01],
       [-8.63667306e-01],
       [-6.65891714e-01],
       [-8.82193121e-01],
       [-8.24237362e-01],
       [-7.09452414e-01],
       [-5.90661884e-01],
       [-5.45223568e-01],
       [-3.91433660e-02],
       [-8.50899515e-01],
       [-8.03833931e-01],
       [-9.86087894e-01],
       [-8.44640793e-01],
       [-7.69536138e-01],
       [-7.48757183e-01],
       [-7.48757183e-01],
       [-6.73652528e-01],
       [-5.2

In [90]:
theta=np.zeros(42)
theta

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
theta.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [92]:
theta=(np.linalg.inv((x.T)@x))@((x.T)@Y)

In [93]:
theta.reshape(-1,1)

array([[ 2.10730385e-01],
       [-4.38917947e-01],
       [ 2.17463761e-01],
       [ 1.04849082e-01],
       [ 3.55688995e-01],
       [ 6.00373122e-01],
       [ 9.23190884e-03],
       [-1.66974703e-01],
       [-5.96258136e-01],
       [ 9.88279962e-02],
       [ 1.31783891e-01],
       [-1.23242139e-01],
       [ 2.02882882e-01],
       [ 3.18890520e-01],
       [ 4.58478855e-02],
       [ 1.34865395e-02],
       [-7.80183235e-02],
       [-2.06914564e-01],
       [-1.46764272e-01],
       [-1.44574025e-01],
       [ 1.33490020e-02],
       [ 5.26231009e-02],
       [ 1.09113018e-01],
       [-7.53884258e-02],
       [-2.32782887e-02],
       [ 1.85760913e-01],
       [ 3.88328223e-02],
       [-1.74776716e-01],
       [ 2.44722947e-01],
       [-2.62205087e-01],
       [-5.16554584e-01],
       [-2.66506319e-01],
       [-4.51870386e-03],
       [-9.35105246e-02],
       [-2.43616533e-01],
       [ 1.87666896e-04],
       [-2.32004351e-02],
       [ 8.79962928e-01],
       [-2.9

In [94]:
y_pred=x.dot(theta)

In [95]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [96]:

r_squared = r2_score(Y, y_pred) 

print(f"R-squared: {r_squared*100}")

R-squared: 91.67035076477153
